# Generated by Django 6.1 on 2026-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={},
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='description',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='phone',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='manuscripts/covers/', verbose_name='تصور مبدئي للغلاف (اختياري)'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='idea',
            field=models.TextField(default='', verbose_name='فكرة العمل أو ملخصه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='phone_number',
            field=models.CharField(default='0000', max_length=20, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='author_name',
            field=models.CharField(max_length=150, verbose_name='اسم المؤلف'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manuscripts/files/', verbose_name='ملف المخطوطة (PDF/Word)'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان العمل'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
