# Generated by Django 6.1 on 2026-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Featured Order'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured on Homepage'),
        ),
    ]
